# Generated by Django 4.0.3 on 2022-03-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisiux', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='cmodel',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='orderrow',
            name='service_id',
        ),
        migrations.AddField(
            model_name='orderrow',
            name='service_id',
            field=models.ManyToManyField(to='servisiux.service'),
        ),
    ]
