# Generated by Django 4.0.3 on 2022-03-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisiux', '0003_alter_orderrow_options_remove_orderrow_service_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
