# Generated by Django 4.0.3 on 2022-03-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisiux', '0004_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.CharField(default='Open order', max_length=50, verbose_name='link'),
        ),
    ]
