# Generated by Django 4.0.3 on 2022-03-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisiux', '0005_order_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='link',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Administruojama'), ('p', 'Paimta'), ('g', 'Galima paimti'), ('r', 'Rezervuota')], default='a', help_text='Statusas', max_length=1),
        ),
    ]
