# Generated by Django 4.0.3 on 2022-03-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisiux', '0006_remove_order_link_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrow',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('e', 'Entered'), ('w', 'Waiting'), ('p', 'In progress'), ('c', 'Completed')], default='e', help_text='Status', max_length=1),
        ),
    ]
