# Generated by Django 4.0.3 on 2022-03-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servisiux', '0008_alter_orderrow_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cover',
            field=models.ImageField(null=True, upload_to='service/cars', verbose_name='Carpic'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carmodel', to='servisiux.carmodel'),
        ),
    ]
