# Generated by Django 4.0.3 on 2022-03-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servisiux', '0009_car_cover_alter_car_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='car_instance_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carorder', to='servisiux.car'),
        ),
    ]
