# Generated by Django 4.0.3 on 2022-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisiux', '0010_alter_order_car_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oras',
            field=models.CharField(blank=True, choices=[('a', 'Geras'), ('b', 'Neskaito')], default='e', help_text='Oras', max_length=1),
        ),
    ]
