# Generated by Django 4.0.3 on 2022-03-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servisiux', '0011_order_oras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oras',
        ),
    ]
