# Generated by Django 4.0.3 on 2022-03-31 17:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('servisiux', '0013_order_due_date_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
